---
- name: Create unific Docker volumes
  community.docker.docker_volume:
    name: "{{ unific_docker_volume_name }}"

- name: Create unific Docker network
  community.docker.docker_network:
    name: "{{ unific_network_name }}"
    driver: "bridge"
    enable_ipv6: "no"
    internal: "no"
    scope: "local"
    ipam_config:
      - subnet: "{{ unific_network_subnet }}"
        gateway: "{{ unific_network_gateway }}"
  when: unific_docker_network_created is not defined

# UDP 3478 Port used for STUN. #REQUIRED
# TCP 5514 Port used for remote syslog capture.
# TCP 8080 Port used for device and controller communication. #REQUIRED
# TCP 8443 Port used for controller GUI/API as seen in a web browser #REQUIRED
# TCP 8880 Port used for HTTP portal redirection.
# TCP 8843 Port used for HTTPS portal redirection.
# TCP 6789 Port used for UniFi mobile speed test. #REQUIRED
# TCP 27117 Port used for local-bound database communication.
# UDP 5656-5699 Ports used by AP-EDU broadcasting.
# UDP 10001 Port used for device discovery #REQUIRED
# UDP 1900 Port used for "Make controller discoverable on L2 network" in controller settings.
- name: UniFi Controller Docker Container
  community.docker.docker_container:
    name: unific
    image: "jacobalberty/unifi:{{ unific_image_tag }}"
    pull: true
    mounts:
      - source: "/etc/localtime"
        target: "/etc/localtime:"
        read_only: true
        type: "bind"
      - source: "/etc/timezone"
        target: "/etc/timezone:"
        read_only: true
        type: "bind"
      - source: "{{ unific_docker_volume_name }}"
        target: "/unifi"
        type: "volume"
    network_mode: "{{ unific_network_name }}"
    networks:
      - name: "{{ unific_network_name }}"
    env:
      TZ: "{{ unific_timezone }}"
    ports:
      - "3478:3478/udp"
      - "8080:8080"
      - "6789:6789"
      - "10001:10001/udp"
      - "1900:1900/udp"
      # - "8443:8443" # Handled by Traefik Proxy
    restart_policy: unless-stopped
    cpus: "{{ unific_cpus }}"
    memory: "{{ unific_memory }}"
    container_default_behavior: no_defaults
    auto_remove: no
    detach: yes
    init: yes
    interactive: no
    paused: no
    privileged: no
    read_only: no
    tty: no
    labels:
      traefik.enable: "{{ unific_available_externally }}"
      traefik.http.routers.unific.rule: "{{ unific_traefik_router_rule | default(omit) }}"
      traefik.http.routers.unific.entrypoints: "{{ unific_traefik_router_entrypoints | default(omit) }}"
      traefik.http.routers.unific.tls: "true"
      traefik.http.routers.unific.tls.certresolver: "{{ unific_traefik_router_tls_certresolver | default(omit) }}"
      traefik.http.routers.unific.tls.domains[0].main: "*.{{ unific_host_domain }}"
      traefik.http.services.unific.loadbalancer.server.scheme: "https"
      traefik.http.services.unific.loadbalancer.server.port: "{{ unific_traefik_https_port | default(omit) }}"
  register: unific_docker_started

- name: Add unific container to any extra networks
  community.docker.docker_network:
    name: "{{ item }}"
    connected:
      - "unific"
    appends: yes
  loop: "{{ unific_docker_extra_networks }}"