collections:
  - name: community.docker
    version: ">=1.2.0,<2"
  - name: community.general
    version: ">=2,<3"

roles:
  - src: geerlingguy.repo-epel
  - src: geerlingguy.pip
  - src: geerlingguy.docker
