---
scenario:
  name: customized

dependency:
  name: galaxy
  options:
    requirements-file: molecule/resources/requirements.yml
    role-file: molecule/resources/requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbooks/converge.yml
  inventory:
    host_vars:
      instance:
        unific_hostname: "unifictest"
        unific_docker_volume_name: "unific-test-data"
        unific_network_name: "utestlan"
        unific_network_subnet: "172.200.3.0/24"
        unific_network_gateway: "172.200.3.1"
        unific_available_externally: "true"


verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
